services:
  db:
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - ./docker/db/sql:/docker-entrypoint-initdb.d
      - pg-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@db.com
      - PGADMIN_DEFAULT_PASSWORD=root
    restart: always
    ports:
      - "5000:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json
    depends_on:
      - "db"
  service:
    profiles: ["all", "service"]
    build:
      context: ./service
    restart: always
    user: "${UID}"
    ports:
      - "3000:3000"
    depends_on:
      - "db"
    volumes:
      - ./service:/service
      - /dev/null:/service/.env
      - node-data:/home/node
    command: ash -c 'yarn install && yarn build && node .'
  app:
    profiles: ["all", "app"]
    build:
      context: ./app
    restart: always
    user: "${UID}"
    ports:
      - "3001:3000"
    depends_on:
      - "service"
    volumes:
      - ./app:/app
      - /dev/null:/service/.env
      - node-data:/home/node
    command: ash -c 'yarn install && yarn dev'
volumes:
  pg-data:
  pgadmin-data:
  node-data: