name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./app/Dockerfile
            image: fastapi_app
          - dockerfile: ./service/Dockerfile
            image: fastapi_service
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build $(dirname ${{ matrix.dockerfile }}) --file ${{ matrix.dockerfile }} --tag ${{ matrix.image }}:$(date +%s)
